# Generated by Django 3.2.14 on 2022-08-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAcceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre comercial de la empresa')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('sitio_web', models.CharField(max_length=200, verbose_name='Sitio web')),
                ('ubicacion', models.CharField(max_length=350, verbose_name='País, Estado y Ciudad')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Usuario administrador')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Numero de Identificación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nit')),
                ('apellido', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('ubicacion', models.CharField(max_length=350, verbose_name='País, Estado y Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAcceso.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nit')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de celular')),
                ('geolocalizacion', models.CharField(max_length=350, verbose_name='Geolocalización')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=8, verbose_name='Estado del punto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAcceso.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAcceso.usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAcceso.horario', verbose_name='Horario de Usuario')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAcceso.sucursal', verbose_name='Sucursal de Empresa')),
            ],
        ),
    ]
