# Generated by Django 3.2.14 on 2022-08-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAcceso', '0002_asignacion_empresa_horario_sucursal_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacion',
            table='Asignaciones',
        ),
    ]
