# Generated by Django 3.2.14 on 2022-08-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAcceso', '0004_alter_asignacion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='hora_finalizacion',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicial',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
