# Generated by Django 3.2.14 on 2022-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAcceso', '0006_user_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8, verbose_name='Estado del punto'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
